- name: Install stuff
  hosts: controlserver
  become: true # I always set become=false in the ansible.cfg
  vars:
    packages:
      - '@virtualization' # there is a group for kvm, virtsh, etc
        #- coreos-installer
      - butane
    services:
      - libvirtd
    domain_path: /opt/kvm/fcos

  tasks:
    - name: Ensure required packages are present
      dnf:
        name: "{{ packages }}"
        state: present
    
    - name: Start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ services }}" # only one service for now

    - name: Get latest Fedora CoreOS version and url
      include_tasks: tasks/getversion.yaml

    - name: Download latest version
      include_tasks: tasks/download.yaml
      vars:
        image_name: "fedora-coreos-{{ fcos_latest }}-qemu.x86_64.qcow2"
        

    - name: Copy ignition template
      template:
        src: templates/simple.yaml
        dest: "{{ domain_path }}/simple.yaml"
    
    - name: Run butane
      command: 
        cmd: butane --pretty --strict simple.yaml -o simple.ign
        chdir: "{{ domain_path }}"
      become: false # no reason to run as root